# Generated by Django 2.2.6 on 2019-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sms_toolkit', '0003_alter_recipient_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliomessage',
            name='exception_message',
            field=models.TextField(blank=True),
        ),
    ]
